---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    keyserver: "{{ apt_key_url }}"
  register: add_repository_key
  ignore_errors: true

- name: Alternative - Add Docker repository key
  shell: "curl -sSL {{ apt_key_url }} | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key

- name: Set up the stable repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes

- name: Start docker
  command:  /etc/init.d/docker start
  ignore_errors: true

# - name: Install docker sdk by pip
#   pip:
#     name: docker-py
#     executable: pip3

- name: Install docker-compose sdk by pip
  pip:
    name: docker-compose
    executable: pip3

# - name: Install docker-py
#   pip:
#     name: docker-py

# - name: Create {{ docker_home }} directory
#   file:
#     path: "{{ docker_home }}"
#     state: directory

...