---
- name: Clean deploy path
  command: rm -r "{{ deploy_path }}/{{ app }}"
  ignore_errors: true
  changed_when: false

- name: Clone AspNetCore.IdentityServer4.Sample 
  git:
    repo: https://github.com/KarateJB/AspNetCore.IdentityServer4.Sample.git
    dest: "{{ deploy_path }}/{{ app }}"
    # version: auth-code-pkce # Checkout the certain branch

...