---
- name: Docker compose up
  docker_compose:
    project_src: '{{ docker_compose_file_path }}'
    build: yes
    nocache: yes
    state: present 
  register: docker_compose_output

- debug:
    var: docker_compose_output

- assert:
    that:
      - "docker_compose_output.ansible_facts.auth['idsrv-auth'].state.running"
      - "docker_compose_output.ansible_facts.backend['idsrv-backend'].state.running"
      - "docker_compose_output.ansible_facts.nginx['idsrv-nginx'].state.running"
      - "docker_compose_output.ansible_facts.openldap['idsrv-openldap'].state.running"
      - "docker_compose_output.ansible_facts.redis['idsrv-redis'].state.running"
 
...