---

- name: Restart modified containers
  command: "docker restart {{ item }}"
  with_items:
    - idsrv-auth
    - idsrv-backend
  when: appsettings_are_updated is succeeded

- name: Delete temparary AppSettings file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/deploy/Auth/{{ appsettings_file_name }}
    - /tmp/deploy/Backend/{{ appsettings_file_name }}
  retries: 3
  delay: 3
  register: temp_configs_are_deleted
  until: temp_configs_are_deleted is succeeded

...