---
- name: Clone app repository(s)
  include: clone.yml

# - name: Docker compose up
#   docker_compose:
#     project_src: '{{ docker_compose_file_path }}'
#     build: yes
#     nocache: yes
#     state: present 
#   register: docker_compose_output

# - debug:
#     var: docker_compose_output
#   # assert:
#   #   that:
#   #     - "idsrv-auth.state.running"
#   #     - "idsrv-backend.state.running"

- name: Create temp directory for configuration files
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: root
    owner: root
  with_items:
    - "/tmp/Deploy/Auth/"
    - "/tmp/Deploy/Backend"

- name: Include vars file
  include_vars: "{{ env }}.yml"
  
- name: Generate Auth Server's AppSettings file
  template:
    src: AppSettings/AppSettings.Auth.j2
    dest: /tmp/deploy/Auth/{{ appsettings_file_name }}

- name: Generate Backend's AppSettings file
  template:
    src: AppSettings/AppSettings.WebApi.j2
    dest: /tmp/deploy/Backend/{{ appsettings_file_name }}


...