---
- name: Clone app repository(s)
  include: 1.clone_ap_repository.yml

- name: Build and run containers
  include: 2.run_containers.yml

- name: Update application configuration
  include: 3.update_ap_config.yml

- name: Update certificate
  include: 4.update_cert.yml 

- name: Restart containers
  include: 5.restart_containers.yml 

- name: Remove temp files
  include: 6.remove_tmp_files.yml 

...