---
- name: Deploy Applications
  vars:
    - machine: dev_hp_omen
    - env: "development"
  hosts: "{{ machine }}"
  gather_facts: no
  roles:
    - { role: app, become: yes }
  vars_files:
    - "roles/app/vars/{{ env }}.yml"