---
- name: Install packages
  apt:
    pkg:
      - yum
      - yum-utils
      - conntrack
    state: latest
    update_cache: true
  notify:

- name: Create temp download dir
  file:
    path: /tmp/Minikube
    state: directory

- name: Download miniKube
  # become: yes
  # become_user: root
  get_url:
    url: "{{ minikube_url }}"
    dest: "{{ minikube_download_path }}"
    mode: 0755

- name: Install minikube
  shell: |
    install "{{ minikube_download_path }}" "{{ minikube_install_path }}"

- name: Download kubectl
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_download_path }}"
    mode: 0755

- name: Install kubectl
  shell: |
    install "{{ kubectl_download_path }}" "{{ kubectl_install_path }}"

- name: Start minukube
  shell: |
    minikube start --driver=none