---
# For all
redis_host: "redis"
redis_port: 6379

# For AppSettings.Auth.j2 only
ldap_host: "openldap"
ldap_port: 389
ldap_is_enable_ssl: "false"
ldap_bind_dn: "cn=admin,dc=example,dc=org"
ldap_bind_credentials: "admin"
ldap_search_base: "dc=example,dc=org"
ldap_search_filter: "(&(objectClass=person)(uid={0}))"
signing_credential:
    default_expiry:
        year: 1
access_token:
    default_absolute_expiry: 3600
    client_credentials_default_absolute_expiry: 360
refresh_token:
    default_absolute_expiry: 36000
    default_sliding_expiry: 3600
open_id:
    allowed_redirect_uris:
        - { host: '{{ ansible_ssh_host }}', port: '5001', uri: '/signin-oidc' }

# For AppSettings.WebApi.j2 only
auth_host: "auth"
auth_port: "6001"
audience: "MyBackendApi2"
client_id: "PolicyBasedBackend"
refresh_discovery_doc_duration: 8

...